name: "Deploy codigo facilito"

on:
  push:
    branches: ["master"]

jobs:
  deploy-codigoFacilito:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v4
      run: echo "Hacemos pull del codigo"
      run: echo "Run migrations"
      run: echo "Generate binaries"
      run: echo "Publish version"
